### ISSUE TITLE
Bài tập OOP sẽ làm ở CI

### ISSUE THREAD

**Issue by vihoangson** [DeRossi/Training_CI#1]
## Bài 1: sử dụng cơ sở dữ liệu Sqlite
- Dùng phần mềm phpliteadmin để quản lý sqlite
  
  > http://www.phpliteadmin.org/
  > http://gyazo.cybridge.jp/8221fee351a6a10cf0cd7cd595aa60f7
  > http://gyazo.cybridge.jp/075a914c325ce8b6cd818c2926a2be5d
- Tạo 1 database trong thư mục applications/models/db/my_sqlite.sqlite
  http://gyazo.cybridge.jp/d573fabaa52f5bdf51baf231cff2686f
  http://gyazo.cybridge.jp/af6773e91f2f94b2c5dfbc2dd1c199f7
- Tạo 1 table "students" với nội dung
  
  > id > number
  > student_name > text
  > student_birth > datetime
  > student_sex > text
  > student_address > text

**Comment by DeRossi** [comment]
phải có folder db thì set chmod 777 mới có ý nghĩa 

$directory = 'application/models/';
↓↓↓
$directory = 'application/models/db/';
